# Generated by Django 3.0.3 on 2020-02-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='cigs_num',
            field=models.PositiveIntegerField(),
        ),
    ]
