version: '3.7'
services:
  angular:
    build: ./gems-app
    command: ng serve --host 0.0.0.0
    environment:
      - ALLOWED_HOSTS=localhost
      - DEBUG=True
    ports:
      - '4200:4200'
      - '45193:45193'
    volumes:
      - ./gems-app:/app
      - angular-node-modules:/gems-app/node_modules
  # api:
  #   build: ./rest_api
  #   command: python manage.py runserver 0.0.0.0:8000
  #   ports:
  #     - '8000:8000'
  #     - '8080:8080'
  #   volumes:
  #     - ./rest_api:/api
  #   depends_on:
  #     - db
  # db:
  #   image: postgres:12.1
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   ports:
  #     - '5432:5432'
volumes:
  # pgdata:
  angular-node-modules:
